# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
                ('open', models.DecimalField(decimal_places=1, max_digits=5)),
                ('high', models.DecimalField(decimal_places=1, max_digits=5)),
                ('low', models.DecimalField(decimal_places=1, max_digits=5)),
                ('change', models.DecimalField(decimal_places=2, max_digits=4)),
                ('val', models.CharField(blank=True, choices=[('dollar', '$')], default='dollar', max_length=64, null=True)),
            ],
        ),
    ]
